language: node_js
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
node_js:
- '5'
before_script:
- npm install -g istanbul
- npm install -g mocha

script: make test-full
after_success:
- make coveralls
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - export CC="gcc-4.9" CXX="g++-4.9"