language: node_js
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
node_js:
- '0.12.2'
before_script:
- npm install -g istanbul
- npm install -g mocha

script: make test-full
after_success:
- make coveralls
